### ISSUE TITLE
[Android] Extra vertical padding in bottom tab bar upon app launch

### ISSUE THREAD

**Issue by ChitrakshTarun** [callstackincubator/react-native-bottom-tabs#228]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Bottom Tab Bar on Android has extra vertical padding when the app is launched. This padding goes away when I minimise the app to the foreground, and re-open it. If I close the app completely and re-open it, the padding returns.

Running on a physical Android device, using a development build created using EAS (issue arises in other builds too).

Image 1: When the app is first launched, it has extra padding.
Image 2: When the app is foregrounded and gone back to, padding goes away.

<div>
<img src="https://github.com/user-attachments/assets/17f97153-cdc0-48a6-b164-7a923c19c7da" height="500">
<img src="https://github.com/user-attachments/assets/670cebd8-3276-4238-bc1b-b1240660f178" height="500">
</div>
 

### Library version

0.78

### Environment info

```shell
System:
  OS: Linux 4.4 Ubuntu 20.04.3 LTS (Focal Fossa)
  CPU: "(16) x64 AMD Ryzen 7 5800H with Radeon Graphics         "
  Memory: 4.23 GB / 15.86 GB
  Shell:
    version: 5.0.17
    path: /bin/bash
Binaries:
  Node:
    version: 20.18.0
    path: ~/.nvm/versions/node/v20.18.0/bin/node
  Yarn:
    version: 1.22.19
    path: /mnt/c/Users/Fevenir/AppData/Roaming/npm/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.18.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.3
    wanted: latest
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.5
    wanted: 0.76.5
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. Create an Expo app and install the react-native-bottom-tabs dependencies.
2. Replace JS tabs with the Native Bottom Tabs.
3. Create a development build for the app.
4. Launch the app on Android. 

### Reproducible sample code

```js
import React from "react";
import { Tabs } from "@/components/NativeBottomTabs";
import { useColorsForUI } from "@/hooks/useColorsForUI";
import { storage } from "@/lib/utils/mmkv";
import { Platform } from "react-native";
import { useMMKVBoolean } from "react-native-mmkv";

export default function TabLayout() {
  const [haptics, setHaptics] = useMMKVBoolean("settings-haptics", storage);
  const { tintColor, backgroundColor, tabBarTintColor } = useColorsForUI();

  return (
    <Tabs
      ignoresTopSafeArea
      hapticFeedbackEnabled={haptics}
      activeIndicatorColor={tabBarTintColor}
      tabBarActiveTintColor={tintColor}
      barTintColor={Platform.select({
        ios: undefined,
        android: backgroundColor,
      })}
    >
      {/* HOME SCREEN - Paces */}
      <Tabs.Screen
        name="(home)"
        options={{
          headerShown: false,
          tabBarLabel: "PaceMan.gg",

          tabBarIcon: Platform.select({
            ios: ({ focused }: { focused: boolean }) =>
              focused ? { sfSymbol: "stopwatch.fill" } : { sfSymbol: "stopwatch" },
            android: ({ focused }) =>
              focused ? require("@/assets/icons/stopwatch.svg") : require("@/assets/icons/stopwatch-outline.svg"),
          }),
        }}
      />

      {/* LEADERBOARD SCREEN */}
      <Tabs.Screen
        name="lb"
        options={{
          headerShown: false,
          tabBarLabel: "Leaderboard",
          tabBarIcon: Platform.select({
            ios: ({ focused }: { focused: boolean }) => (focused ? { sfSymbol: "medal.fill" } : { sfSymbol: "medal" }),
            android: ({ focused }) =>
              focused ? require("@/assets/icons/trophy.svg") : require("@/assets/icons/trophy-outline.svg"),
          }),
        }}
        initialParams={{ id: "monthly" }}
      />

      {/* STATS SCREEN */}
      <Tabs.Screen
        name="stats"
        options={{
          headerShown: false,
          tabBarLabel: "Stats",
          tabBarIcon: Platform.select({
            ios: ({ focused }: { focused: boolean }) =>
              focused ? { sfSymbol: "chart.bar.fill" } : { sfSymbol: "chart.bar" },
            android: ({ focused }) =>
              focused ? require("@/assets/icons/stats-chart.svg") : require("@/assets/icons/stats-chart-outline.svg"),
          }),
        }}
      />
    </Tabs>
  );
}
```

**Comment by ChitrakshTarun** [comment]
This would be my first GitHub issue so please let me know if I should submit anything other information regarding it.
For context, this implementation is from the following project: https://github.com/ChitrakshTarun/PaceManApp

Thank you in advance!

**Comment by okwasniewski** [comment]
Hey, @ChitrakshTarun 

Thanks for creating the issue. Can you check if it happens on a device without the bottom buttons (system navigation bar)? 

I've tested only without it so it might be an issue

**Comment by ChitrakshTarun** [comment]
Hi @okwasniewski, thank you for the response!
Yep, the issue seems to persist when system navigation bar is enabled as well, but the padding is a little less subtle. Placing them side by side can give a better idea:

Image 1: When the app is first launched.
Image 2: When the app is foregrounded and gone back to.

<div>
<img src="https://github.com/user-attachments/assets/9464cf7b-44f4-4952-a7d1-6d358823b5a1" height="500">
<img src="https://github.com/user-attachments/assets/12d543bd-e5ae-4011-b00d-b46a5f9ece7c" height="500">
</div>

**Comment by okwasniewski** [comment]
Thanks for checking it! I'm planning to refactor how the bottom bar is placed on the screen inside of the library, hopefully this refactor will address this issue. Will keep you posted.

**Comment by guillaumehcht** [comment]
Hey just commenting to follow the topic as I'm experiencing a similar issue it seems! :)

**Comment by okwasniewski** [comment]
Hey @ChitrakshTarun @guillaumehcht I've published a canary version of 0.8.0 [`0.8.0-canary-20250115141919`](https://www.npmjs.com/package/react-native-bottom-tabs/v/0.8.0-canary-20250115141919) if you could please test if this version solves your issues it would help me a lot 🙏

**Comment by ChitrakshTarun** [comment]
Hi, seems like I still have the same issue occurring. However this time, the extra padding has a different color than the set backgroundColor property. 
Also tried updating `react-native-edge-to-edge` to the latest version as well as setting `enforceNavigationBarContrast` to false, however it seems like the issue persists. 


`Device`: OnePlus 6T
`OS`: Android 11

Here is the tested repository and the build:

- [Repository](https://github.com/ChitrakshTarun/PaceManApp/tree/dev) (`dev` Branch)
- [EAS Build](https://expo.dev/accounts/chitrakshtarun/projects/PaceManGG/builds/4aade21d-04b8-470a-9b7a-e7b97c2b1b9a) (Development Build)

Screen recording recreating the error:

<video src="https://github.com/user-attachments/assets/9642f9c1-8c10-4c0a-ae9f-5e00a9c3b76b">

**Comment by okwasniewski** [comment]
@ChitrakshTarun Thanks for checking it. Can you create a separate example app to see if the issue persists? 

Maybe it's something in your App that's causing this jump and it will help us track it down

**Comment by ChitrakshTarun** [comment]
Sure, I'll try spinning up a new project and see if the issue still persists, then update back in this issue accordingly

**Comment by ChitrakshTarun** [comment]
Hi @okwasniewski, tried spinning up a new expo project with the canary build of the package and the issue seems to persist. 

Additional packages apart from default expo packages:
- @bottom-tabs/react-navigation@0.8.0-canary-20250115141919
- react-native-bottom-tabs@0.8.0-canary-20250115141919
- react-native-edge-to-edge@1.4.0

Notes:
- Scaffolded using `npx create-expo-app@latest` with the default template.
- [Repository](https://github.com/ChitrakshTarun/Bottom-Tabs-Padding-Test/)
- [(tabs)/_layout.tsx file](https://github.com/ChitrakshTarun/Bottom-Tabs-Padding-Test/blob/main/app/(tabs)/_layout.tsx)
- [EAS Build](https://expo.dev/accounts/chitrakshtarun/projects/Bottom-Tabs-Padding-Test/builds/d5e0ccfe-0b1d-491d-a68b-2490b5da1f84) (Development Build)

Screen Recording:
<video src="https://github.com/user-attachments/assets/e2d6de22-1ce2-493f-b9e1-312ebf801c27">

**Comment by okwasniewski** [comment]
@ChitrakshTarun I found the root cause, using `<StatusBar style="auto" />` causes this shift(!). 

Looks like changing StatusBar properties messes with the sizing. I will investigate further but as a workaround you can test without it.

**Comment by okwasniewski** [comment]
@ChitrakshTarun looks like using `<StatusBar/>` + RN Edge To Edge conflict with each other.. Maybe @zoontek seen this before but for me it looks like they shouldn't be used together. 

Here is an example of just rendering a view, and calling `Alert` when layout happens. 

The root cause of this is that when StatusBar + Edge To Edge is used bottom navigation is first rendered **under** the system navigation bar and then it's pushed up. The video below shows that when returning to the app Edge To Edge starts working properly and then measurements are fixed. 

https://github.com/user-attachments/assets/ed3f9d6d-66bf-4b75-9eb5-6db0260fb4c7

**Comment by zoontek** [comment]
Hello folks!

Yes I'm aware, `StatusBar` breaks edge-to-edge (not only when enabled by `react-native-edge-to-edge`), that's why I provide `SystemBars`:

![image](https://github.com/user-attachments/assets/b436eb0c-92eb-4cf9-a425-b0474c598f0d)

The fault to `Window.statusBarShow`: https://github.com/facebook/react-native/blob/a0411eebe284895ccaa11e7eab8a69bd2f7e7e53/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/view/WindowUtil.kt#L59

More infos: https://github.com/facebook/react-native/pull/47554

TL;DR: only use `SystemBars`

**Comment by okwasniewski** [comment]
Thank you for clarifying @zoontek 😄

**Comment by okwasniewski** [comment]
Released a new RC: `0.8.0-canary-20250117162505` that should be final canary release before stable 0.8.0, would be great if you can check it out one more time!

**Comment by ChitrakshTarun** [comment]
Hi, tested out the new RC on the same bottom-tabs test app and it seems to work fine! 
Tested with `<SystemBars style="auto" />` from `react-native-edge-to-edge`, similar to the previous discussion, and it seems to work as intended.

[Repository](https://github.com/ChitrakshTarun/Bottom-Tabs-Padding-Test/)
[EAS Build](https://expo.dev/accounts/chitrakshtarun/projects/Bottom-Tabs-Padding-Test/builds/b6b90725-ef0b-4ac5-93f9-a04651028c7f) (Development Build)

<video src="https://github.com/user-attachments/assets/166c1c22-c5d1-4d26-9de3-bc73ef3f7198">

**Comment by ChitrakshTarun** [comment]
Sounds good! Thank you for the amazing work with this library! 🐐 🚀
